---
version: 2

sphinx:
  configuration: docs/conf.py

# https://github.com/readthedocs/readthedocs.org/issues/4912#issuecomment-1110189914
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_create_environment:
      - asdf plugin add poetry
      - asdf install poetry latest
      - asdf global poetry latest
      - poetry config virtualenvs.create false
    post_install:
      - poetry install
