---
version: 2

sphinx:
  configuration: docs/conf.py

# https://github.com/readthedocs/readthedocs.org/issues/4912#issuecomment-1110189914
# https://github.com/readthedocs/readthedocs.org/issues/4912#issuecomment-1143587902
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    post_install:
      - pip install poetry
      - poetry config virtualenvs.create false
      - poetry install
