[tool.poetry]
name = "nornir_paramiko"
version = "0.2.0"
description = ""
authors = ["Devon Mar <devonm@mdmm.ca>"]

[tool.poetry.plugins."nornir.plugins.connections"]
"paramiko" = "nornir_paramiko.plugins.connections:Paramiko"

[tool.poetry.dependencies]
python = "^3.7"
paramiko = "^2.7"
nornir = "^3.0.0"
scp = "^0.13.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
Sphinx = "^4.5.0"
sphinx-rtd-theme = "^1.0.0"
sphinx-autodoc-typehints = "^1.18.3"
black = "^22.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
