[tool.poetry]
name = "nornir_paramiko"
version = "0.2.0"
description = ""
authors = ["Devon Mar <devonm@mdmm.ca>"]

[tool.poetry.plugins."nornir.plugins.connections"]
"paramiko" = "nornir_paramiko.plugins.connections:Paramiko"

[tool.poetry.dependencies]
python = "^3.6"
paramiko = "^2.7"
nornir = "^3.0.0"
scp = "^0.13.3"
sphinx = {version = "^3", optional = true}
sphinx-rtd-theme = {version = "^0.5.2", optional = true}
sphinx-autodoc-typehints = {version = "^1.12.0", optional = true}

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.extras]
docs = ["sphinx", "sphinx-rtd-theme", "sphinx-autodoc-typehints"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
